[package]
name = "yecpaperwallet"
version = "0.1.0"
authors = ["Ycash Foundation"]
edition = "2018"
    
[dependencies]
clap = "2.33.0"
zecpaperlib = { path = "../lib" }
json = "0.11.14"
printpdf = "0.2.8"
