[package]
name = "qtlib"
version = "0.1.0"
authors = ["Ycash Foundation"]
edition = "2018"

[lib]
name = "yecpaperrust"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.58"
yecpaperlib = { path = "../../lib" }
